// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADK7k0L9hM6X-My9M1OPSeXP8g21Yy-ng',
    appId: '1:2424897465:web:d60504bfc452d170e40068',
    messagingSenderId: '2424897465',
    projectId: 'yem-event-signatures',
    authDomain: 'yem-event-signatures.firebaseapp.com',
    storageBucket: 'yem-event-signatures.firebasestorage.app',
    measurementId: 'G-TE30SGTJTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl_-WRJq_WWKJbMIFxqbUqghG7NRXleXA',
    appId: '1:2424897465:android:b006e5a6f6d7803ce40068',
    messagingSenderId: '2424897465',
    projectId: 'yem-event-signatures',
    storageBucket: 'yem-event-signatures.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczenJkLS9df3vxX7yNmWO9e6_rDLc9U0',
    appId: '1:2424897465:ios:24be000711c92a14e40068',
    messagingSenderId: '2424897465',
    projectId: 'yem-event-signatures',
    storageBucket: 'yem-event-signatures.firebasestorage.app',
    iosBundleId: 'com.example.yemEventsSignature',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczenJkLS9df3vxX7yNmWO9e6_rDLc9U0',
    appId: '1:2424897465:ios:24be000711c92a14e40068',
    messagingSenderId: '2424897465',
    projectId: 'yem-event-signatures',
    storageBucket: 'yem-event-signatures.firebasestorage.app',
    iosBundleId: 'com.example.yemEventsSignature',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADK7k0L9hM6X-My9M1OPSeXP8g21Yy-ng',
    appId: '1:2424897465:web:92f5aa668026be7fe40068',
    messagingSenderId: '2424897465',
    projectId: 'yem-event-signatures',
    authDomain: 'yem-event-signatures.firebaseapp.com',
    storageBucket: 'yem-event-signatures.firebasestorage.app',
    measurementId: 'G-0SCZW2HZ0E',
  );
}
